[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
once_cell = "1.20.2"
nom = "7.1.3"

[dev-dependencies]
test-case = "3.3.1"

[dependencies.bitflags]
version = "2.6.0"

